# Use root/example as user/password credentials
version: '3.1'

services:
  database:
    image: sarathchandra24/mysql
    container_name: own-compose-mysql
    command: mysqld --user=root --verbose
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABSE: eidiko
    ports:
      - 3308:3306
  tomcat:
    image: sarathchandra24/tomcat-9-13j
    container_name: own-compose-tomcat
    restart: always
    ports:
      - 9080:8080

# "docker-compose build" it is for creating an image
#
#  docker network connect bridge MysqlDB
#docker run --name mysqlDB -e MYSQL_ROOT_PASSWORD="" -d mysql:latest